"""
实验一 配置文件
配置 GitHub Token、目标项目列表、API 参数等
"""

import os
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".env"))

# ========== GitHub API 配置 ==========
# 从 https://github.com/settings/tokens 生成 Personal Access Token
# 不需要任何权限（public repo 只读即可）
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

# API 请求间隔（秒），防止触发限流
REQUEST_DELAY = 0.5

# ========== 目标项目列表 ==========
# 每个元素：(owner, repo_name, 项目描述)
# 选择标准：大型开源项目，活跃度高，有 AI 相关 PR
TARGET_REPOS = [
    ("kubernetes", "kubernetes", "容器编排平台，PR 审查流程严格规范"),
    ("pytorch", "pytorch", "深度学习框架，有 AI 生成代码和 AI Review"),
    ("tensorflow", "tensorflow", "深度学习框架，大型社区活跃"),
    ("microsoft", "vscode", "大型 IDE 项目，代码审查规范"),
    ("langchain-ai", "langchain", "LLM 应用框架，与 AI 紧密相关"),
]

# ========== 数据采集参数 ==========
PR_PER_REPO = 300          # 每个项目获取的 PR 数量
PR_STATE = "all"           # PR 状态: "open" / "closed" / "all"
SORT = "created"           # 排序方式: "created" / "updated" / "popularity"
DIRECTION = "desc"         # 排序方向: "asc" / "desc"

# ========== 文件路径 ==========

# 数据根目录
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")          # 原始 API 数据
PROCESSED_DIR = os.path.join(DATA_DIR, "processed")  # 处理后的 CSV
FIGURES_DIR = os.path.join(BASE_DIR, "figures")   # 可视化图片

# 确保目录存在
for dir_path in [DATA_DIR, RAW_DIR, PROCESSED_DIR, FIGURES_DIR]:
    os.makedirs(dir_path, exist_ok=True)

# ========== AI Reviewer 关键词 ==========
# 常见的 AI/Bot Reviewer 标识
AI_REVIEWER_KEYWORDS = [
    "bot", "code-review", "codereview", "ai-review",
    "copilot", "chatgpt", "gpt", "deepseek",
    "sonar", "codacy", "codeclimate", "lgtm",
]

# ========== Bot 作者关键词（不算 AI，直接排除）==========
BOT_AUTHOR_KEYWORDS = [
    "bot", "dependabot", "renovate", "codecov",
    "github-actions", "imgbot", "allcontributors",
]

# ========== AI 生成代码检测关键词 ==========
# 在 commit message / PR body / PR title / labels 中匹配
AI_KEYWORDS = [
    # 明确声明 AI 生成
    "co-authored-by: copilot",
    "co-authored-by: github copilot",
    "generated by copilot",
    "generated by ai",
    "ai-generated",
    "generated by chatgpt",
    "generated by gpt",
    "generated by claude",
    "generated by cursor",
    "generated by deepseek",
    "generated by gemini",
    # 提到 AI 工具
    "copilot",
    "chatgpt",
    "github copilot",
    "claude",
    "cursor",
    "deepseek",
    "gemini",
    "codex",
    "tabnine",
    "codeium",
    "windsurf",
]