"""
实验二 配置文件
配置路径、AI 检测关键词等
"""

import os
import certifi
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".env"))

# ========== SSL 证书配置（与 lab1 保持一致）==========
os.environ["SSL_CERT_FILE"] = certifi.where()
os.environ["REQUESTS_CA_BUNDLE"] = certifi.where()

# ========== 路径配置 ==========
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LAB1_DIR = os.path.join(os.path.dirname(BASE_DIR), "lab1")
LAB1_RAW_DIR = os.path.join(LAB1_DIR, "data", "raw")

DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")
HUMAN_DIR = os.path.join(RAW_DIR, "human")
NON_HUMAN_DIR = os.path.join(RAW_DIR, "non_human")
CODE_DIR = os.path.join(DATA_DIR, "code")

for dir_path in [DATA_DIR, RAW_DIR, HUMAN_DIR, NON_HUMAN_DIR, CODE_DIR]:
    os.makedirs(dir_path, exist_ok=True)

# ========== 目标项目列表 ==========
TARGET_REPOS = [
    ("kubernetes", "kubernetes"),
    ("pytorch", "pytorch"),
    ("tensorflow", "tensorflow"),
    ("microsoft", "vscode"),
    ("langchain-ai", "langchain"),
]

# ========== Bot 作者关键词（直接排除，不算 AI 也不算人类）==========
BOT_AUTHOR_KEYWORDS = [
    "bot", "dependabot", "renovate", "codecov",
    "github-actions", "imgbot", "allcontributors",
]

# ========== AI 生成代码检测关键词 ==========
AI_KEYWORDS = [
    "co-authored-by: copilot",
    "co-authored-by: github copilot",
    "generated by copilot",
    "generated by ai",
    "ai-generated",
    "generated by chatgpt",
    "generated by gpt",
    "generated by claude",
    "generated by cursor",
    "generated by deepseek",
    "generated by gemini",
    "copilot",
    "chatgpt",
    "github copilot",
    "claude",
    "cursor",
    "deepseek",
    "gemini",
    "codex",
    "tabnine",
    "codeium",
    "windsurf",
]

# ========== GitHub API 配置 ==========
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REQUEST_DELAY = 0.5

# ========== 代理配置（国内环境需要）==========
# 支持 http 代理，常见端口: Clash(7890), V2Ray(10809), SS(1080)
# 留空则自动检测环境变量 HTTP_PROXY / HTTPS_PROXY
HTTP_PROXY = None
HTTPS_PROXY = None

# ========== 支持的语言扩展名映射 ==========
SUPPORTED_EXTENSIONS = {
    ".go": "Go",
    ".py": "Python", ".pyi": "Python",
    ".js": "JavaScript", ".jsx": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TypeScript",
    ".java": "Java",
    ".c": "C", ".h": "C",
    ".cpp": "C++", ".cc": "C++", ".cxx": "C++",
    ".hpp": "C++",
}

# ========== 代码输出目录 ==========
HUMAN_CODE_DIR = os.path.join(CODE_DIR, "human")

# ========== AST 输出目录 ==========
AST_DIR = os.path.join(DATA_DIR, "ast")
HUMAN_AST_DIR = os.path.join(AST_DIR, "human")

# ========== CFG 输出目录 ==========
CFG_DIR = os.path.join(DATA_DIR, "cfg")
HUMAN_CFG_DIR = os.path.join(CFG_DIR, "human")

# 创建输出目录
for dir_path in [AST_DIR, HUMAN_AST_DIR, CFG_DIR, HUMAN_CFG_DIR]:
    os.makedirs(dir_path, exist_ok=True)

# ========== tree-sitter 语言名称映射 ==========
TREE_SITTER_LANG_MAP = {
    "Go": "go",
    "Python": "python",
    "JavaScript": "javascript",
    "TypeScript": "typescript",
    "Java": "java",
    "C": "c",
    "C++": "cpp",
}

# 常见控制流节点类型（覆盖大多数语言）
CONTROL_FLOW_TYPES = {
    "if_statement", "for_statement", "while_statement", "do_statement",
    "switch_statement", "case_statement", "return_statement",
    "break_statement", "continue_statement", "goto_statement",
    "try_statement", "catch_clause", "finally_clause", "with_statement"
}

# ========== 特征提取输出目录 ==========
FEATURES_DIR = os.path.join(DATA_DIR, "features")
os.makedirs(FEATURES_DIR, exist_ok=True)

# ========== 模型与结果输出目录 ==========
MODELS_DIR = os.path.join(DATA_DIR, "models")
RESULTS_DIR = os.path.join(DATA_DIR, "results")
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)